name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0' # Cambia según tu versión

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish Project
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to IIS
      uses: appleboy/ssh-action@v0.5.6
      with:
        host: ${{ secrets.WINDOWS_SERVER_HOST }}
        username: ${{ secrets.WINDOWS_SERVER_USER }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        script: |
          New-Item -ItemType Directory -Force -Path "C:\inetpub\wwwroot\mi-aplicacion"
          Copy-Item -Path ./publish/* -Destination "C:\inetpub\wwwroot\mi-aplicacion" -Recurse
          Import-Module WebAdministration
          Stop-WebAppPool -Name "DefaultAppPool"
          Start-WebAppPool -Name "DefaultAppPool"
